import 'package:bona_blog/features/article/data/model/article_model.dart';

List<Article> dummyGetAllArticles() => <Article>[
      Article(
          articleId: 1,
          author: "Williano",
          title: "Sports is the Best1 Sports is the Best1 Sports is the Best1",
          imageURL: "assets/images/error.jpg",
          category: "Sports",
          body: "Test",
          numberOfViews: 5000,
          readTime: 200,
          datePublishedOn: "April 15, 2019"),
      Article(
          articleId: 2,
          author: "Williano Williano",
          title:
              "Software is the Best1 Sports is the Best1 Sports is the Best1 ",
          imageURL: "assets/images/se.jpg",
          category: "Software Engineering",
          body: "Test",
          numberOfViews: 5000,
          readTime: 200,
          datePublishedOn: "May 15, 2019"),
      Article(
          articleId: 3,
          author: "William Kwabla",
          title: "Art is the Best1",
          imageURL: "assets/images/art.jpg",
          category: "Art",
          body: "Test",
          numberOfViews: 5000,
          readTime: 200,
          datePublishedOn: "Jan 15, 2019"),
      Article(
          articleId: 4,
          author: "Bill",
          title: "Food is the Best1",
          imageURL: "assets/images/food.jpg",
          category: "Food",
          body: "Test",
          numberOfViews: 5000,
          readTime: 200,
          datePublishedOn: "Feb 15, 2020"),
      Article(
          articleId: 5,
          author: "Seema",
          title: "Design is the Best1",
          imageURL: "assets/images/design.jpg",
          category: "Design",
          body: "Test",
          numberOfViews: 5000,
          readTime: 200,
          datePublishedOn: "April 15, 2019"),
      Article(
          articleId: 6,
          author: "Khalil",
          title: "Education is the Best1",
          imageURL: "assets/images/education.jpg",
          category: "Education",
          body: "Test",
          numberOfViews: 5000,
          readTime: 200,
          datePublishedOn: "April 15, 2019"),
      Article(
          articleId: 7,
          author: "Dr. Tansel Halic",
          title: "Entertainment is the Best1",
          imageURL: "assets/images/Entertainment.jpg",
          category: "Entertainment",
          body: "Test",
          numberOfViews: 5000,
          readTime: 200,
          datePublishedOn: "April 15, 2019"),
      Article(
          articleId: 8,
          author: "Adiza Rasheed",
          title: "Programming is the Best1",
          imageURL: "assets/images/programming.jpg",
          category: "Programming",
          body: "Test",
          numberOfViews: 5000,
          readTime: 200,
          datePublishedOn: "April 15, 2019"),
      Article(
          articleId: 9,
          author: "Kwabena Yeboah",
          title: "Sports is the Best1",
          imageURL: "assets/images/error.jpg",
          category: "Sports",
          body: "Test",
          numberOfViews: 5000,
          readTime: 200,
          datePublishedOn: "April 15, 2019"),
      Article(
          articleId: 10,
          author: "Oliver Boamah",
          title: "Bugs is the Best1",
          imageURL: "assets/images/error4.jpg",
          category: "Bug",
          body: "Test",
          numberOfViews: 5000,
          readTime: 200,
          datePublishedOn: "April 15, 2019"),
    ];
